# Generated by Django 3.2.8 on 2021-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название слайда для себя')),
                ('title', models.CharField(max_length=180, verbose_name='заголовок на слайде')),
                ('description', models.CharField(max_length=500, verbose_name='добваить описание')),
                ('img', models.ImageField(upload_to='slider/', verbose_name='добавить изобрадение')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'слайдеры',
            },
        ),
    ]
