# Generated by Django 3.2.8 on 2021-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название продукта')),
                ('price', models.FloatField(verbose_name='цена')),
                ('img', models.ImageField(upload_to='slider/', verbose_name='добавить изобрадение')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'слайды'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='номер слайда начиня с 0 по порядку'),
        ),
    ]
