# Generated by Django 3.2.8 on 2021-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211108_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Овощи'), ('Fruit', 'Фрукты'), ('Dairy_products', 'Молочные продукты'), ('Berries', 'Ягоды'), ('Beekeeping_Products', 'Продукты пчеловодства'), ('Seedling', 'Рассада'), ('Flowers_plants', 'Цветы и декоративные расстения')], default='Vegetables', max_length=30, verbose_name='категория продукта'),
        ),
    ]
